let redflowers: Sprite = null
let mySprite = sprites.create(img`
    . . . . . . . . . . . . . . 
    e e e . . . . e e e . . . . 
    e d d e . . e d d e . . . . 
    e 3 d d e e d d 3 e . . . . 
    e 3 3 d d d d 3 3 e . . . . 
    e 3 3 d d d d 3 3 e . . . . 
    e d d d d d d d d e . . . . 
    e d d d d d d d d e . e e e 
    e d 9 d d d 9 d d e . e d e 
    e d d d f d d d d e e e d e 
    . e 3 3 3 3 3 3 d d d d d e 
    . e d d d d d d d e e e e . 
    . . e d d d e d e . . . . . 
    . . e e e e e e e . . . . . 
    `, SpriteKind.Player)
tiles.setTilemap(tilemap`level1`)
controller.moveSprite(mySprite, 100, 100)
mySprite.ay = 500
mySprite.setPosition(30, 200)
scene.cameraFollowSprite(mySprite)
game.onUpdateInterval(1000, function () {
    redflowers = sprites.createProjectileFromSide(img`
        ....................
        ....................
        ....................
        ....................
        ....................
        ....................
        ....................
        ....................
        ....................
        ....................
        ....................
        ....................
        .......2.2.2........
        .......22222........
        .......22222........
        .......22222........
        .........7..........
        .........7..........
        .........7..........
        .........7..........
        .........7..........
        ....................
        ....................
        ....................
        ....................
        ....................
        ....................
        ....................
        ....................
        ....................
        `, 50, 50)
    redflowers.x = randint(5, 155)
    redflowers.setKind(SpriteKind.Enemy)
})
